
package testtool.view.questionmanager;

import java.awt.Window;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import testtool.model.administration.Course;
import testtool.model.administration.User;
import testtool.model.questionmanager.QuestionDifficulty;
import testtool.model.questionmanager.QuestionManager;
import testtool.model.questionmanager.QuestionType;
import testtool.view.TestToolDialog;


/**
 * The view class for the question search dialog.
 * 
 * @author Ian Smith-Grove
 */
public class QuestionSearchUI extends TestToolDialog {

    /**
     * 
     */
    private QuestionManager model;
    
    /**
     * 
     */
    private ManageQuestionsUI view;
    
    /**
     * Creates new form QuestionSearchUI.
     */
    public QuestionSearchUI(QuestionManager model, ManageQuestionsUI view) {
        super("Test Tool / Advanced Question Search");
        this.model = model;
        this.view = view;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      LabelKeywords = new javax.swing.JLabel();
      LabelType = new javax.swing.JLabel();
      LabelCourse = new javax.swing.JLabel();
      LabelDifficulty = new javax.swing.JLabel();
      LabelAuthor = new javax.swing.JLabel();
      KeywordsInput = new javax.swing.JTextField();
      TypeComboBox = new javax.swing.JComboBox<>(QuestionType.values());
      CourseComboBox = new javax.swing.JComboBox<>(model.buildCourseList());
      DifficultyComboBox = new javax.swing.JComboBox<>(QuestionDifficulty.values());
      AuthorComboBox = new javax.swing.JComboBox<>(model.buildTeacherList());
      ButtonSearch = new javax.swing.JButton();
      ButtonClear = new javax.swing.JButton();
      ButtonCancel = new javax.swing.JButton();

      LabelKeywords.setText("Keywords");

      LabelType.setText("Type");

      LabelCourse.setText("Course");

      LabelDifficulty.setText("Difficulty");

      LabelAuthor.setText("Author");

      TypeComboBox.setSelectedIndex(-1);

      CourseComboBox.setSelectedIndex(-1);

      DifficultyComboBox.setSelectedIndex(-1);

      AuthorComboBox.setSelectedIndex(-1);

      ButtonSearch.setText("Search");
      ButtonSearch.setMaximumSize(new java.awt.Dimension(88, 28));
      ButtonSearch.setMinimumSize(new java.awt.Dimension(88, 28));
      ButtonSearch.setPreferredSize(new java.awt.Dimension(88, 28));
      ButtonSearch.setRequestFocusEnabled(false);
      ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonSearchActionPerformed(evt);
         }
      });

      ButtonClear.setText("Clear");
      ButtonClear.setMaximumSize(new java.awt.Dimension(88, 28));
      ButtonClear.setMinimumSize(new java.awt.Dimension(88, 28));
      ButtonClear.setPreferredSize(new java.awt.Dimension(88, 28));
      ButtonClear.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonClearActionPerformed(evt);
         }
      });

      ButtonCancel.setText("Cancel");
      ButtonCancel.setMaximumSize(new java.awt.Dimension(88, 28));
      ButtonCancel.setMinimumSize(new java.awt.Dimension(88, 28));
      ButtonCancel.setPreferredSize(new java.awt.Dimension(88, 28));
      ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonCancelActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(TypeComboBox, 0, 176, Short.MAX_VALUE)
                           .addComponent(DifficultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(LabelDifficulty)
                           .addComponent(LabelType))
                        .addGap(0, 0, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(LabelAuthor)
                     .addComponent(AuthorComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(LabelCourse)
                     .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(KeywordsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(LabelKeywords)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(LabelKeywords)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(KeywordsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(LabelType)
               .addComponent(LabelCourse))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(LabelAuthor)
               .addComponent(LabelDifficulty))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(AuthorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(DifficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called when the search button is clicked.
     * It will take the parameters provided in the form and use them to search the database for matching questions.
     */
    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        String[] keywords = KeywordsInput.getText().split("[\\s,]+");
        QuestionType type = (QuestionType) TypeComboBox.getSelectedItem();
        Course course = (Course) CourseComboBox.getSelectedItem();
        QuestionDifficulty difficulty = (QuestionDifficulty) DifficultyComboBox.getSelectedItem();
        User createdBy = (User) AuthorComboBox.getSelectedItem();

        model.searchQuestion(keywords, type, course, difficulty, createdBy);
        close();
    }//GEN-LAST:event_ButtonSearchActionPerformed

    /**
     * clears the fields by setting everything to blank strings.
     * @param evt
     */
    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        KeywordsInput.setText("");
        TypeComboBox.setSelectedIndex(-1);
        CourseComboBox.setSelectedIndex(-1);
        AuthorComboBox.setSelectedIndex(-1);
        DifficultyComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_ButtonClearActionPerformed

    /**
     * will end the current window, preventing any further actions
     * and closes the window.
     * @param evt
     */
    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        close();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    /**
     * closes the current dialog screen
     */
    private void close() {
        Window window = SwingUtilities.getWindowAncestor(this);
        JDialog dialog = (JDialog) window;
        dialog.dispose();
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<User> AuthorComboBox;
   private javax.swing.JButton ButtonCancel;
   private javax.swing.JButton ButtonClear;
   private javax.swing.JButton ButtonSearch;
   private javax.swing.JComboBox<Course> CourseComboBox;
   private javax.swing.JComboBox<QuestionDifficulty> DifficultyComboBox;
   private javax.swing.JTextField KeywordsInput;
   private javax.swing.JLabel LabelAuthor;
   private javax.swing.JLabel LabelCourse;
   private javax.swing.JLabel LabelDifficulty;
   private javax.swing.JLabel LabelKeywords;
   private javax.swing.JLabel LabelType;
   private javax.swing.JComboBox<QuestionType> TypeComboBox;
   // End of variables declaration//GEN-END:variables

}
