/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testtool.view.administration;

import testtool.model.administration.Administration;
import testtool.view.TestToolScreen;

/**
 *
 * @author Mogwai
 */
public class EditCourseUI extends TestToolScreen {

    private Administration model;
    private String title;
    private String dept;
    private int number = -1;
    /**
     * Creates new form EditCourseUI
     */
    public EditCourseUI(Administration model) {
	super("Add Course");
        this.model = model;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deptBlank = new javax.swing.JTextField();
        numberBlank = new javax.swing.JTextField();
        LabelHeader = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        LabelDept = new javax.swing.JLabel();
        LabelNumber = new javax.swing.JLabel();
        titleBlank = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        deptBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptBlankActionPerformed(evt);
            }
        });

        numberBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBlankActionPerformed(evt);
            }
        });

        LabelHeader.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LabelHeader.setForeground(new java.awt.Color(255, 255, 255));
        LabelHeader.setText("Edit Course");

        LabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitle.setText("Course Title:");

        LabelDept.setForeground(new java.awt.Color(255, 255, 255));
        LabelDept.setText("Department:");

        LabelNumber.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumber.setText("Course Number:");

        titleBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleBlankActionPerformed(evt);
            }
        });

        createButton.setText("OK");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titleBlank, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNumber)
                                    .addComponent(LabelDept))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deptBlank, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numberBlank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelHeader)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleBlank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptBlank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDept))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberBlank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumber))
                .addGap(28, 28, 28)
                .addComponent(createButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        this.title = titleBlank.getText();
        this.dept = deptBlank.getText();
        this.number = Integer.parseInt(numberBlank.getText());
        
        if (this.title != null) {
            System.out.println(title);

        }
        if (this.dept != null) {
            System.out.println(dept);
        }

        if (this.number != -1) {
            System.out.println(number);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void titleBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleBlankActionPerformed

    }//GEN-LAST:event_titleBlankActionPerformed

    private void deptBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptBlankActionPerformed

    }//GEN-LAST:event_deptBlankActionPerformed

    private void numberBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBlankActionPerformed

    }//GEN-LAST:event_numberBlankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDept;
    private javax.swing.JLabel LabelHeader;
    private javax.swing.JLabel LabelNumber;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField deptBlank;
    private javax.swing.JTextField numberBlank;
    private javax.swing.JTextField titleBlank;
    // End of variables declaration//GEN-END:variables
}
