/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testtool.view.administration;

import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import testtool.model.administration.Administration;
import testtool.model.administration.Course;
import testtool.view.TestToolScreen;

/**
 *
 * @author Mogwai
 */
public class ManageCoursesUI extends TestToolScreen {


    /**
     * 
     */
    private Administration model;
    /**
     * 
     */
    private Collection<Course> courseList;
    
    public ManageCoursesUI(Administration administration) {
        super("TestTool / Manage Courses");
        initComponents();
        
        CourseTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.model = administration;
        
        
                DefaultTableModel table = (DefaultTableModel) CourseTable.getModel();

        while (table.getRowCount() > 0)
            table.removeRow(0);

        //String[] keywords = SearchField.getText().split("[\\s,]+");
        Collection<Course> courses = model.getCourses();
        System.out.println(courses);
        
        for (Course course: courses) {
            table.addRow(course.toArray());
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        ButtonDelete = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Department", "Course Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CourseTable.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(CourseTable);
        if (CourseTable.getColumnModel().getColumnCount() > 0) {
            CourseTable.getColumnModel().getColumn(0).setResizable(false);
            CourseTable.getColumnModel().getColumn(1).setResizable(false);
            CourseTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course Bank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(ButtonDelete)
                        .addGap(56, 56, 56)
                        .addComponent(ButtonEdit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonEdit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        courseList = model.getCourses();
        DefaultTableModel table = (DefaultTableModel) CourseTable.getModel();
        int index = CourseTable.getSelectedRow();
        int dialogResult = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to permanently delete the selected Course?", "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (dialogResult == JOptionPane.YES_OPTION) {
            String title = (String) CourseTable.getModel().getValueAt(index, 0);
            String dept = (String) CourseTable.getModel().getValueAt(index, 1);
            int number = (int) CourseTable.getModel().getValueAt(index, 2);
           
            table.removeRow(index);
            System.out.println("title: " + title);
            System.out.println("dept: " + dept);
            System.out.println("number: " + number);
            model.deleteCourse(title, dept, number);
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
Window window = SwingUtilities.getWindowAncestor(this);
       JFrame frame = (JFrame) window;
       
       JDialog test = new JDialog(frame, Dialog.ModalityType.DOCUMENT_MODAL);
       test.getContentPane().setLayout(new FlowLayout());
       test.setTitle("Edit Course");
       
       EditCourseUI panel = new EditCourseUI(model);
       test.getContentPane().add(panel, BorderLayout.EAST);
       
       test.setResizable(false);
       
       test.pack();
       test.setVisible(true);        
    }//GEN-LAST:event_ButtonEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JTable CourseTable;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
