/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testtool.view.administration;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.Window;
import testtool.model.administration.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import testtool.model.administration.Administration;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author tjyung
 */
public class ManageUsersUI extends javax.swing.JPanel {

    private final Administration admin;
    /**
     * Creates new form ManageUsersUI
     */
    public ManageUsersUI(Administration ad) {
        initComponents();
        admin = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        ButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        ButtonView = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        ButtonSearch.setText("Search");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Password", "Id", "Permissions"
            }
        ));
        jScrollPane1.setViewportView(UserTable);

        ButtonView.setText("View");
        ButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSearch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ButtonView)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonDelete)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonView)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonDelete))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
    * When an element in the table is selected all the buttons  
    * 
    * @param evt Action Event is passed to the method.
    */
   private void TestTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
      //System.out.println("HIT!: " + Arrays.toString(QuestionTable.getSelectedRows()));
      if (UserTable.getSelectedRowCount() == 1) {
         ButtonView.setEnabled(true);
         ButtonEdit.setEnabled(true);
         ButtonDelete.setEnabled(true);
      } else if (UserTable.getSelectedRowCount() > 1) {
         ButtonView.setEnabled(false);
         ButtonEdit.setEnabled(false);
         ButtonDelete.setEnabled(true);
      } else {
         ButtonView.setEnabled(false);
         ButtonEdit.setEnabled(false);
         ButtonDelete.setEnabled(false);
      }
   } 
    
    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        DefaultTableModel table = (DefaultTableModel) UserTable.getModel();
      
      while (table.getRowCount() > 0)
         table.removeRow(0);
   
      ArrayList<User> userList = new ArrayList<User>();
      userList.add(admin.searchUsers(jTextField1.getText()).get(0));

      if (userList == null) {
         JOptionPane.showMessageDialog(null,
            "Sorry! No results were found using term: " + jTextField1.getText().toUpperCase() +
               ". Try using different keywords",
            "Attention",
            JOptionPane.WARNING_MESSAGE);
      }
     
        table.addRow(userList.get(0).toArray());
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void ButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewActionPerformed
      Window window = SwingUtilities.getWindowAncestor(this);
      int index = UserTable.getSelectedRow();
      JFrame frame = (JFrame) window;

      JDialog test = new JDialog(frame, Dialog.ModalityType.DOCUMENT_MODAL);
      test.getContentPane().setLayout(new FlowLayout());
      test.setTitle("Test Tool / Manage User / View User");

      ViewUser panel = new ViewUser(userList.get(index));
      test.getContentPane().add(panel, BorderLayout.EAST);

      //test.setUndecorated(true);
      //test.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
      test.setResizable(false);

      test.pack();
      test.setVisible(true);
    }//GEN-LAST:event_ButtonViewActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);
      int index = UserTable.getSelectedRow();
      JFrame frame = (JFrame) window;

      JDialog test = new JDialog(frame, Dialog.ModalityType.DOCUMENT_MODAL);
      test.getContentPane().setLayout(new FlowLayout());
      test.setTitle("Test Tool / Manage Users / Edit Users");

      ViewUser panel = new ViewUser(userList.get(index));
      test.getContentPane().add(panel, BorderLayout.EAST);

      //test.setUndecorated(true);
      //test.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
      test.setResizable(false);

      test.pack();
      test.setVisible(true);
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
      DefaultTableModel table = (DefaultTableModel) UserTable.getModel();
      int index = UserTable.getSelectedRow();
      int dialogResult = JOptionPane.showConfirmDialog (null, 
         "Are you sure you want to permanently delete the selected tests?", "Warning", 
         JOptionPane.YES_NO_OPTION,
         JOptionPane.WARNING_MESSAGE);
     
      if(dialogResult == JOptionPane.YES_OPTION) {
         table.removeRow(index);
         admin.deleteUser(userList.get(index));
      }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private Administration model;
    private ArrayList<User> userList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonView;
    private javax.swing.JTable UserTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
