/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testtool.view.grademanager;

import testtool.view.TestToolDialog;
import testtool.model.grademanager.*;

import javax.swing.table.DefaultTableModel;
import testtool.view.TestToolScreen;
/**
 *
 * @author Eliane
 */
public class GradeSubmissionsUI extends TestToolDialog {

    TestToolScreen top;
    GradeManager manager;
    GradeTestUI ui;
    /**
     * Creates new form GradeSubmissionsUI
     */
    public GradeSubmissionsUI(TestToolScreen top, GradeManager manager, GradeTestUI ui) {
        super("Grade Submissions");
        initComponents();

        this.ui = ui;
        this.top = top;
        this.manager = manager;
        GradeStudentButton.setEnabled(false);
        GradeQuestionButton.setEnabled(false);
         
        DefaultTableModel students = (DefaultTableModel) StudentTable.getModel();

        for (TestSubmission t : manager.activeTest.test.submissions) {
            students.addRow(new Object[]{ t.student.username, t.student.firstname + " " + t.student.lastname, t.totalGradeScore});
        }

        DefaultTableModel questions = (DefaultTableModel) QuestionTable.getModel();
        for (GradeQuestionStatistics g : manager.activeTest.qStats) {
          questions.addRow(new Object[] {g.questionNumber, g.points, g.maxScored, g.avgScored, g.numberGraded });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuestionTable = new javax.swing.JTable();
        GradeStudentButton = new javax.swing.JButton();
        GradeQuestionButton = new javax.swing.JButton();
        SwitchTestButton = new javax.swing.JButton();

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false // edited java instead of form, remeber to make fields not editable
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(StudentTable);
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });

        QuestionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "pts", "max", "avg", "graded"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false // I edited the java directly because I didn't have access to netbeans
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        QuestionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(QuestionTable);
        QuestionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionTableMouseClicked(evt);
            }
        });

        GradeStudentButton.setText("Grade Student"); // Added action listener by hand cause no netbeans
        GradeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeStudentButtonActionPerformed(evt);
            }
        });

        GradeQuestionButton.setText("Grade Question"); // added action listener by hand
        GradeQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeQuestionButtonActionPerformed(evt);
            }
        });

        SwitchTestButton.setText("Switch Test");
        SwitchTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(GradeStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(SwitchTestButton)
                .addGap(88, 88, 88)
                .addComponent(GradeQuestionButton)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradeStudentButton)
                    .addComponent(GradeQuestionButton)
                    .addComponent(SwitchTestButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void GradeStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeStudentButtonActionPerformed
        // TODO add your handling code here:
        int selected = StudentTable.getSelectedRow();
        TestSubmission submission = manager.activeTest.test.submissions.toArray(new TestSubmission[0])[selected];
        cleanup();
        manager.activeTest.GradeTestSubmission(submission);
        System.out.println("We are here");
        ui.GradeByStudent();

    }//GEN-LAST:event_GradeStudentButtonActionPerformed
    
    private void GradeQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeQuestionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeQuestionButtonActionPerformed

    private void SwitchTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwitchTestButtonActionPerformed

    /**
     * activate the 'ok' button if a course is selected, otherwise it remains
     * turned off
     * @param evt
     */
    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        //System.out.println("HIT!: " + Arrays.toString(QuestionTable.getSelectedRows()));
      GradeStudentButton.setEnabled(true);
    }//GEN-LAST:event_StudentTableMouseClicked
    
    /**
     * activate the 'ok' button if a course is selected, otherwise it remains
     * turned off
     * @param evt
     */
    private void QuestionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionTableMouseClicked
        //System.out.println("HIT!: " + Arrays.toString(QuestionTable.getSelectedRows()));
      GradeQuestionButton.setEnabled(true);
    }//GEN-LAST:event_QuestionTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GradeQuestionButton;
    private javax.swing.JButton GradeStudentButton;
    private javax.swing.JTable QuestionTable;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton SwitchTestButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
