package testtool.view;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import testtool.TestTool;

/****
 *
 * Class TestToolMenuBar creates and diplsyas the menubar at the top of the testtool.
 *
 * @author Ian Smith-Grove (ismithgr@calpoly.edu)
 */
public class TestToolMenuBar extends JMenuBar {

    /**
     * reference to model for fun stuff
     */
    TestTool testtool;
    
    /**
     * This constructor creates a new TestToolMenuBar and initializes
     * the swing components.
     */
    public TestToolMenuBar(TestTool testtool) {
        this.testtool = testtool;
        initComponents();
    }
    
    /**
     * This method displays the tool-bar on the passed frame
     * @param frame window on which the tool-bar is displayed
     */
    public void draw(JFrame frame) {
        frame.setJMenuBar(this);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        File = new javax.swing.JMenu();
        LogoutMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ExitMenuItem = new javax.swing.JMenuItem();
        Navigate = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenuItem();

        File.setText("File");

        LogoutMenuItem.setText("Logout");
        LogoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuItemActionPerformed(evt);
            }
        });
        File.add(LogoutMenuItem);
        File.add(jSeparator2);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        File.add(ExitMenuItem);

        add(File);

        Navigate.setText("Navigate");

        HomeMenuItem.setText("Home");
        HomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenuItemActionPerformed(evt);
            }
        });
        Navigate.add(HomeMenuItem);

        add(Navigate);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Log out of the current user and return to the login screen
     * @param evt
     */
    private void LogoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuItemActionPerformed
        /*Window window = SwingUtilities.getWindowAncestor(this);
        JFrame frame = (JFrame) window;
        frame.getContentPane().setLayout(new FlowLayout());
        frame.setTitle("Login");
        
        this.setVisible(false);
        frame.getContentPane().removeAll();
        frame.revalidate();
        frame.repaint();
        
        LoginUI thing = new LoginUI(testtool);
        frame.getContentPane().add(thing, BorderLayout.CENTER); 
                        
        frame.pack();
        frame.setVisible(true);*/
        
        Window window = SwingUtilities.getWindowAncestor(this);
        JFrame frame = (JFrame) window;
        frame.dispose();
        JFrame displayFrame = new JFrame("Login");

        displayFrame.setResizable(false);
        LoginUI thing = new LoginUI(testtool);
        displayFrame.getContentPane().add(thing, BorderLayout.CENTER);
        displayFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        displayFrame.pack();

        displayFrame.setVisible(true);
        
        testtool.login.logout();
    }//GEN-LAST:event_LogoutMenuItemActionPerformed

    /**
     * method will go back to the home screenn when home button pressed.
     * @param evt
     */
    private void HomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenuItemActionPerformed
        JFrame frame = this.getFrame();
        AdministratorUI thing = new AdministratorUI(testtool);
        
        frame.getContentPane().removeAll();
        thing.draw(frame);
        
    }//GEN-LAST:event_HomeMenuItemActionPerformed

    /**
     * exit button will close the screen and exit the program
     * @param evt
     */
    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        this.getFrame().dispose();
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    /**
     * 
     * @return The display frame of the Test Tool
     */
    private javax.swing.JFrame getFrame() {
        Window window = SwingUtilities.getWindowAncestor(this);
        return (JFrame) window;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem HomeMenuItem;
    private javax.swing.JMenuItem LogoutMenuItem;
    private javax.swing.JMenu Navigate;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
