
package testtool.view.testmanager;

import testtool.model.testmanager.Test;
import testtool.view.TestToolDialog;

/**
 * Class TestSearchUI provides the user with a way to view a specific test.
 * 
 * @author Peter Georgiev
 */
public class ViewTestUI extends TestToolDialog {

   /**
    * Creates new form ViewTest
    * 
    * @param test Test object
    */
   public ViewTestUI(Test test) {
      super("Manage Tests / View Test");
      
      initComponents();
      
      this.title.setText(test.getTitle());
      this.introduction.setText(test.getIntroduction());
      this.introduction.setEditable(false);
      this.numberOfQuestionsLabel.setText(Integer.toString(test.getNumQuestions()));
      this.timeToCompleteLabel.setText(Integer.toString(test.getTimeToComplete()) + " min");
      this.courseLabel.setText(test.getCourse().department + " " + test.getCourse().number);
      
      if (test.getNumQuestions() == 0) 
         nextButton.setEnabled(false);
       else 
         nextButton.setEnabled(true);
      
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      title = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      introduction = new javax.swing.JTextPane();
      jLabel1 = new javax.swing.JLabel();
      numberOfQuestionsLabel = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      timeToCompleteLabel = new javax.swing.JLabel();
      nextButton = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      courseLabel = new javax.swing.JLabel();

      title.setFont(new java.awt.Font("Noteworthy", 0, 18)); // NOI18N
      title.setText("jLabel1");

      jScrollPane2.setViewportView(introduction);

      jLabel1.setText("Number of questions: ");

      numberOfQuestionsLabel.setText("jLabel2");

      jLabel3.setText("Time to complete: ");

      timeToCompleteLabel.setText("jLabel4");

      nextButton.setText("Next");

      jLabel2.setText("Course: ");

      courseLabel.setText("jLabel4");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(147, 147, 147)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel1)
                           .addComponent(nextButton)
                           .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(numberOfQuestionsLabel)
                           .addComponent(timeToCompleteLabel)
                           .addComponent(courseLabel)))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(94, 94, 94))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(54, 54, 54)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(51, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(title)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(courseLabel))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(numberOfQuestionsLabel))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(timeToCompleteLabel))
            .addGap(18, 18, 18)
            .addComponent(nextButton)
            .addGap(25, 25, 25))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel courseLabel;
   private javax.swing.JTextPane introduction;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JButton nextButton;
   private javax.swing.JLabel numberOfQuestionsLabel;
   private javax.swing.JLabel timeToCompleteLabel;
   private javax.swing.JLabel title;
   // End of variables declaration//GEN-END:variables
}
